### ISSUE TITLE
Other Web Edits

### ISSUE THREAD

**Issue by michelle-easter** [MindMakersProject/website#12]
- [x] Sequentially, can the page be changed such that the order of the tabs at the top is the same as the order of the content in the page? Ie: the tabs run as: 1. Home 2. Mission 3. Team 4. Media 5. Events: 6: Contact but the content appears as: 1. Home, 2. Mission 3. Team 4. Media 5. Contact 6: Events (Along the page, events and contact should be swapped such that contact is last)
- [x]  Formatting-wise, it seems inconsistent to have “Mission” and “About” sections with only a “Mission” tab at the top. Can we put the mission as a sub heading under “About” and make the tab at the top say “About” instead of “Mission”?
- [x] Under “Team” for Juan’s bio, after his name there are two periods instead of one. Please remove one.
- [x] Under “Team”, “OUR SPONSORS” should be changed to “SPONSORS”
- [x] Under “Team”, Bobak and Melody should be swapped such that Bobak is after Isis and before Melody (Advisors grouped together)

**Comment by isisAnchalee** [comment]
done
