### ISSUE TITLE
Video Integration

### ISSUE THREAD

**Issue by michelle-easter** [MindMakersProject/website#13]
Two Vimeo videos need to be embedded (or something) into the media section of the site. Ideally there can be a thumbnail or something such that the video can be expanded or viewed in the frame, and the description should be unique for each video 
- [ ] // Video title:
  {
  Mind Makers - Making Mindful Matters Matter
  }
  // Video link:
  {
  https://vimeo.com/149455112
  }
  //Description:
  {
  We are all about the power of teamwork and knowledge-sharing! The Mind Makers motivation and project plan was announced at the December 18th TEDxLA Salon event and the founding members took the opportunity to show by example how new skills can be passed from engineers to anyone willing to learn. To launch the initiative, the team made magic by learning how to lay out and solder circuits to make RF controlled LED bows and bow ties. Check out the video to see them exchange skills and discuss why they care about making mindful matters, matter.
  }
- [ ] // Video title:
  {
  MM + Girl Scouts - Workshop Tips for Max Impact: 
  }
  //Video link:
  {
  https://vimeo.com/user51304114/workshoptips
  }
  //Description:
  {
  The Mind Makers team hosted an electronics workshop on Valentine's Day weekend to teach two Girl Scouts robotics teams, the Javabots and the Honor Roll, how to make remote controlled LED bows and bow ties! Want to host an engineering workshop? Take some tips from our team to make it a success!
  }

**Comment by wcjohnson11** [comment]
starting this now
