### ISSUE TITLE
Add Advisor to Team Section

### ISSUE THREAD

**Issue by michelle-easter** [MindMakersProject/website#20]
- [ ] Add Charles Dandino as an advisor to the team section. He should go after Bobak in the first section. His photo is below, and his bio should read:

{
Charles Dandino.  Advisor.  
Mechanical engineer with experience on the Curiosity and Mars 2020 (future) Rovers, and currently working on the Asteroid Redirect Mission which will snatch a large asteroid out of orbit and put it in orbit around the moon for exploration.  After nearly 20 years of boring schooling, Charles is eager to contribute to a fast-paced, hands-on STEAM learning project.  Charles has learned more through projects and mentors than he has through books.  Your results may vary, but probably not.
}

![charlesdandino200x200](https://cloud.githubusercontent.com/assets/15645850/15264839/ecefed9e-192c-11e6-9deb-ce14c5c05a10.jpg)

**Comment by wcjohnson11** [comment]
resolved
