### ISSUE TITLE
Job Listings Images

### ISSUE THREAD

**Issue by michelle-easter** [MindMakersProject/website#52]
- [ ] Make folder in appropriate place on Github for Julie's graphics and upload:

![mm_adverts3](https://cloud.githubusercontent.com/assets/15645850/20252983/e2b35862-a9db-11e6-83a8-4abf6c38e2cd.jpg)
![mm_adverts4](https://cloud.githubusercontent.com/assets/15645850/20252978/e2acd3d4-a9db-11e6-820e-9dbb5cbbd317.jpg)
![mm_adverts5](https://cloud.githubusercontent.com/assets/15645850/20252980/e2af436c-a9db-11e6-9a77-43ca4d1f9895.jpg)
![mm_adverts6](https://cloud.githubusercontent.com/assets/15645850/20252979/e2ae54b6-a9db-11e6-8710-18755d6ab680.jpg)
![mm_adverts7](https://cloud.githubusercontent.com/assets/15645850/20252981/e2af96d2-a9db-11e6-9689-399d1b2cc26e.jpg)
![mm_adverts](https://cloud.githubusercontent.com/assets/15645850/20252982/e2aff5f0-a9db-11e6-8118-8b0f383f4b94.jpg)
![mm_adverts2](https://cloud.githubusercontent.com/assets/15645850/20252984/e2bdee4e-a9db-11e6-9617-c338731228a8.jpg)

**Comment by wcjohnson11** [comment]
These can be found in `Website-BE/photos/ads/...`
