### ISSUE TITLE
Framing Adjustment for Media Viewing

### ISSUE THREAD

**Issue by michelle-easter** [MindMakersProject/website#54]
When "Media" is selected, the automatic framing doesn't make the different album options visible, so it could be easy to miss the fact that there are multiple albums, for both the photos and the videos. Also, once selected, the word "Media" in the title itself is chopped off by the Mind Makers logo. See screenshots below. 

- [ ] Some re-framing should be done (potentially shrinking the viewing window?) to make (at least) the following visible in the frame:
- Full "Media" title 
- Viewing frame to see currently selected video/photo
- Description of album (Same description for video should appear for corresponding photo album) (see checklist item below)
- Other album/video options (including scroll arrows when applicable)

- [ ] Add album description for each photo album that corresponds with video description (similar to how description of event appears below videos, the corresponding event description should appear below each photo album selection

![photoscreenshot](https://cloud.githubusercontent.com/assets/15645850/20254762/31dc7986-a9ec-11e6-8d5c-539cea47636f.JPG)
![vidscreenshot](https://cloud.githubusercontent.com/assets/15645850/20254763/31dca2d0-a9ec-11e6-8a1d-ae8f4a2ee713.JPG)

**Comment by wcjohnson11** [comment]
This is done. Making some small css tweaks and will deploy tonight
