### ISSUE TITLE
Fix Framing of "Get Involved" Section

### ISSUE THREAD

**Issue by michelle-easter** [MindMakersProject/website#74]
- [x] Fix default framing shown when "Get Involved" is clicked on. Page should jump down to "Get Involved" title (not "Pasadena, CA"). See attached screenshot.

![capture](https://cloud.githubusercontent.com/assets/15645850/20642542/57cc24c8-b3c6-11e6-9142-0088066b5858.JPG)

**Comment by wcjohnson11** [comment]
fixed
